it-at-m/muc-patternlab-vue

docs/GettingStarted.mdx, package.json, src/index.ts
=> 72 fix style exports

src/components/Intro/MucIntro.stories.ts, src/components/Intro/MucIntro.vue
fix layout of muc-intro to custom vertical
=> :recycle: :lipstick: recreate mucintro-styling for webcomponents

public/assets/temporary/custom-style.css
Short description or comments
**Reference**
Issues #XXX
=> release merge

package-lock.json, src/components/Banner/MucBanner.stories.ts, src/components/Banner/MucBanner.vue
Short description or comments
**Reference**
Issues #XXX
=> :sparkles: new success variant of muc-banner

src/components/Banner/MucBanner.vue
Short description or comments
**Reference**
Issues #XXX
=> deleted color css #135

README.md, src/components/Banner/MucBanner.vue, src/components/BuisnessHours/MucBusinessHours.vue, src/components/Button/MucButton.vue, src/components/Callout/MucCallout.vue, src/components/Comment/MucComment.vue, src/components/Icon/MucIcon.vue, src/components/Intro/MucIntro.vue
=> :lipstick: changed css-class of mucicon and provided optional override #104

src/components/Comment/MucComment.vue
Issues #165
- introduced computed property which limits the props.rating to min / max
=> :bug: added computed rating with min-max limits

src/components/Link/MucLink.stories.ts, src/components/Link/MucLink.vue, src/components/Link/index.ts, src/components/index.ts
Issues #182
- added component
- added story
=> ✨ 182 link component

package.json
=> :bug: fixed typo in fontfaces export #194

src/components/Form/MucSelect.vue, src/composables/useOnClickOutside.ts
Filter function in select component
**Reference**
Issues #206
=> 206 filter function in select component

src/components/Intro/MucIntro.vue
#205
See title :D
**Reference**
closes #205
=> :bug: reduce width of muc-intro content only on >lg displays

src/components/Form/MucCounter.stories.ts, src/components/Form/MucCounter.vue, src/components/Form/index.ts, src/components/index.ts
Add component to select a number with buttons
**Reference**
Issues #186
=> :sparkles: 186 number input component

src/components/Form/MucSelect.stories.ts, src/components/Form/MucSelect.vue, src/components/Form/MucSelectItem.vue, src/components/Form/MucSelectTypes.ts
Add the handling of lists of objects to select component.
**Reference**
Issues #210
=> :sparkles: 210 handling of objects in select component

src/components/PercentageSpinner/MucPercentageSpinner.stories.ts, src/components/PercentageSpinner/MucPercentageSpinner.vue, src/components/PercentageSpinner/index.ts, src/components/index.ts
This introduces a percentage spinner that represents a loading progress. The size is adjustable. The progress can be passed as an attribute.
**Reference**
Issues MPDZBS-842
=> Percentage spinner that represents a loading progress

src/components/PercentageSpinner/MucPercentageSpinner.vue
Fixes the bug, that the Spinner does not show "0%".
Introduces reactive prop destructuring.
=> Bugfix PercentageSpinner

src/components/Form/MucCounter.vue
Add tabindex and aria-labels to counter component.
**Reference**
Issues #252
=> :sparkles: 252 muccounter accessibility

src/components/Comment/MucCommentText.stories.ts, src/components/Comment/MucCommentText.vue
- reverted incorrect code line
- used this issue to improve example
**Reference**
Issues #295
=> :bug: 295 bug revert this line

.coderabbit.yaml
=> :wrench: change tone of coderabbit, no more accent

package-lock.json, package.json, patches/@splidejs+vue-splide+0.6.12.patch
=> :ambulance: fix build errors behind proxy using official vue-splide package with patch-package to fix ts-errors

src/components/Form/MucSelect.vue
Short description or comments
**Reference**
Issues #XXX
=> :bug: fix choices class not working in webcomponent
